### ISSUE TITLE
Consider not caching failed builds

### ISSUE THREAD

**Issue by ctrochalakis** [skroutz/mistry#45]
I think that it makes more sense not to cache build failures, most of the time those would be transient errors that should be retried next time someone asks for that build.

In that case we might want to keep the build directory (in a `failed` subdirectory?) for debugging purposes.

**Comment by agis** [comment]
To illustrate the issue, assume the following scenario:

1. a user schedules a job
2. the build fails because of a transient error (eg. network issue when doing a `git fetch`)
3. the user wants to re-schedule the job so that it can complete successfully (since the error was transient)

Expected:

> The user should be able to re-schedule the job

Actual:

> The result cache kicks in and the job cannot be re-scheduled.

The current workaround is to pass a random job parameter so that the result cache is invalidated. However, this is not always feasible since a user might not have control over the job parameters. For example, in our deployment process, a capistrano task calls the client and there is no way to alter the job parameters despite of committing to the repo and re-deploying.
